# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: xteams

builds:
  - id: xteams
    builder: rust
    binary: xteams
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
